# Generated by Django 3.0.8 on 2021-01-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201112_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='background_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
