# Generated by Django 3.0.8 on 2021-02-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_emailactivationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('column', 'index')},
        ),
    ]
