# Generated by Django 3.0.8 on 2021-02-09 23:30

from django.db import migrations


def set_column_indexes(apps, schema_editor):
    Column = apps.get_model('api', 'TableColumn')
    Task = apps.get_model('api', 'Task')
    for column in Column.objects.all():
        tasks = list(column.tasks.all())
        for index, task in enumerate(tasks):
            task.index = index
        Task.objects.bulk_update(tasks, ['index'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210209_2329'),
    ]

    operations = [
        migrations.RunPython(set_column_indexes)
    ]
