# Generated by Django 3.0.8 on 2021-02-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210210_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablecolumn',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
