version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - db.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: backend/
    entrypoint: ./backend-entrypoint.prod.sh
    env_file:
      - db.env
    volumes:
      - './backend:/backend'
    depends_on:
      - db
  frontend:
    command: serve -s build
    environment:
      - NODE_ENV=production
    build:
      context: frontend/
      dockerfile: Dockerfile.prod
  celery:
    build: backend/
    entrypoint: ./celery-entrypoint.sh
    env_file:
      - db.env
    volumes:
      - './backend:/backend'
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  nginx:
    build: ./nginx
    volumes:
      - './backend/staticfiles:/backend/static'
    ports:
      - 80:80
    depends_on:
      - backend

